Repository lxzLocus/ASEticle-Backend, pull requests merged in 2024-07, with the labels that each got.

#1 [Add]IEEEのスクレイピング処理追加
  .env.example
  app/module/__init__.py
  app/module/ieee.py
  config/__init__.py
  config/locales/ja.yml
  config/localization.py
  config/routes.py
  requirements.txt
Labels: 優先度 - 高, 新機能追加, 修正待ち

#2 [Add] Arxivのスクレイピング処理追加
  app/module/arxiv.py
Labels: 優先度 - 高, 新機能追加

#6 [fix]ACM例外処理追加
  app/module/acm.py
Labels: 画面・機能修正
